In [1]:
# Import the numpy library
import numpy as np


In [2]:
# Task 1: Create an array of natural numbers from 1 to 10
vector_10 = np.arange(1, 11)
print("One-dimensional array (first 10 natural numbers):")
print(vector_10)


One-dimensional array (first 10 natural numbers):
[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# Task 2: Create a 3x3 matrix filled with zeros
matrix_3x3 = np.zeros((3, 3), dtype=int)
print("3x3 matrix filled with zeros:")
print(matrix_3x3)


3x3 matrix filled with zeros:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
# Task 3: Create a 5x5 matrix with random integers from 1 to 10
matrix_5x5 = np.random.randint(1, 11, size=(5, 5))
print("5x5 matrix with random integers from 1 to 10:")
print(matrix_5x5)


5x5 matrix with random integers from 1 to 10:
[[ 1  4  3  8  8]
 [ 9  3  3  8  3]
 [ 8  8  6  9  1]
 [ 1  9 10  2  2]
 [ 2  9  8  6  8]]


In [5]:
# Task 4: Create a 4x4 matrix with random floats from 0 to 1
matrix_4x4 = np.random.rand(4, 4)
print("4x4 matrix with random floats between 0 and 1:")
print(matrix_4x4)


4x4 matrix with random floats between 0 and 1:
[[0.61446398 0.5109793  0.09767252 0.88931283]
 [0.77855701 0.70047891 0.61695315 0.33975529]
 [0.80946326 0.9636937  0.84669108 0.55355488]
 [0.38766902 0.04940372 0.33189721 0.95702212]]


In [6]:
# Task 5: Create two vectors of size 5 with random integers from 1 to 10
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

print("First vector:")
print(array1)
print("Second vector:")
print(array2)

# Element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Element-wise addition (array1 + array2):")
print(addition)
print("Element-wise subtraction (array1 - array2):")
print(subtraction)
print("Element-wise multiplication (array1 * array2):")
print(multiplication)


First vector:
[3 6 3 6 8]
Second vector:
[5 9 3 2 2]
Element-wise addition (array1 + array2):
[ 8 15  6  8 10]
Element-wise subtraction (array1 - array2):
[-2 -3  0  4  6]
Element-wise multiplication (array1 * array2):
[15 54  9 12 16]


In [7]:
# Task 6: Create two vectors of size 7 with random floats
vec1 = np.random.rand(7)
vec2 = np.random.rand(7)

print("First vector (size 7):")
print(vec1)
print("Second vector (size 7):")
print(vec2)

# Calculate the dot product
scalar_product = np.dot(vec1, vec2)
print("Dot (scalar) product of the vectors:")
print(scalar_product)


First vector (size 7):
[0.04550056 0.01909403 0.9906668  0.15514504 0.68747048 0.26233706
 0.6893059 ]
Second vector (size 7):
[0.83014052 0.04357915 0.60668763 0.52563787 0.41360582 0.72597454
 0.93226504]
Dot (scalar) product of the vectors:
1.8385869741041363


In [8]:
# Task 7: Create a 2x2 matrix and a 2x3 matrix with random integers from 1 to 10
mat_2x2 = np.random.randint(1, 11, size=(2, 2))
mat_2x3 = np.random.randint(1, 11, size=(2, 3))

print("2x2 matrix:")
print(mat_2x2)
print("2x3 matrix:")
print(mat_2x3)

# Multiply the 2x2 matrix with the 2x3 matrix (resulting in a 2x3 matrix)
product_7 = np.dot(mat_2x2, mat_2x3)
print("Result of multiplying 2x2 and 2x3 matrices:")
print(product_7)


2x2 matrix:
[[2 8]
 [6 4]]
2x3 matrix:
[[6 2 6]
 [8 3 2]]
Result of multiplying 2x2 and 2x3 matrices:
[[76 28 28]
 [68 24 44]]


In [9]:
# Task 8: Create a 3x3 matrix with random integers from 1 to 10
matrix_3x3_rand = np.random.randint(1, 11, size=(3, 3))
print("3x3 matrix:")
print(matrix_3x3_rand)

# Calculate the inverse of the matrix (if it is non-singular)
try:
    inv_matrix = np.linalg.inv(matrix_3x3_rand)
    print("Inverse matrix:")
    print(inv_matrix)
except np.linalg.LinAlgError:
    print("The matrix is singular and does not have an inverse.")


3x3 matrix:
[[ 9  1  9]
 [ 4 10  6]
 [ 1  9  8]]
Inverse matrix:
[[ 0.05882353  0.16515837 -0.19004525]
 [-0.05882353  0.14253394 -0.04072398]
 [ 0.05882353 -0.18099548  0.19457014]]


In [10]:
# Task 9: Create a 4x4 matrix with random floats from 0 to 1
matrix_4x4_rand = np.random.rand(4, 4)
print("4x4 matrix:")
print(matrix_4x4_rand)

# Transpose the matrix
transpose_9 = matrix_4x4_rand.T
print("Transposed matrix:")
print(transpose_9)


4x4 matrix:
[[0.2151746  0.02566071 0.17778754 0.1159069 ]
 [0.52581659 0.43583462 0.2816181  0.65346429]
 [0.98874515 0.80984182 0.64474654 0.36425547]
 [0.85609444 0.08814351 0.72981363 0.10089888]]
Transposed matrix:
[[0.2151746  0.52581659 0.98874515 0.85609444]
 [0.02566071 0.43583462 0.80984182 0.08814351]
 [0.17778754 0.2816181  0.64474654 0.72981363]
 [0.1159069  0.65346429 0.36425547 0.10089888]]


In [11]:
# Task 10: Create a 3x4 matrix and a vector of size 4 with random integers from 1 to 10
matrix_3x4 = np.random.randint(1, 11, size=(3, 4))
vector_4 = np.random.randint(1, 11, size=4)

print("3x4 matrix:")
print(matrix_3x4)
print("Vector (size 4):")
print(vector_4)

# Multiply the matrix by the vector (resulting in a vector of size 3)
result_10 = np.dot(matrix_3x4, vector_4)
print("Result of multiplying the matrix by the vector:")
print(result_10)


3x4 matrix:
[[ 6  2  8  1]
 [ 6  2  3  9]
 [ 7 10  2  5]]
Vector (size 4):
[7 3 4 1]
Result of multiplying the matrix by the vector:
[81 69 92]


In [12]:
# Task 11: Create a 2x3 matrix and a vector of size 3 with random floats from 0 to 1
matrix_2x3 = np.random.rand(2, 3)
vector_3 = np.random.rand(3)

print("2x3 matrix:")
print(matrix_2x3)
print("Vector (size 3):")
print(vector_3)

# Multiply the matrix by the vector (resulting in a vector of size 2)
result_11 = np.dot(matrix_2x3, vector_3)
print("Result of multiplying the matrix by the vector:")
print(result_11)


2x3 matrix:
[[0.46968807 0.75229561 0.925076  ]
 [0.55734139 0.55305126 0.42498568]]
Vector (size 3):
[0.04626568 0.44991155 0.26045001]
Result of multiplying the matrix by the vector:
[0.60113297 0.38529745]


In [13]:
# Task 12: Create two 2x2 matrices with random integers from 1 to 10
mat_a = np.random.randint(1, 11, size=(2, 2))
mat_b = np.random.randint(1, 11, size=(2, 2))

print("Matrix A:")
print(mat_a)
print("Matrix B:")
print(mat_b)

# Element-wise multiplication of the matrices
elementwise_product = np.multiply(mat_a, mat_b)
print("Element-wise product of matrices A and B:")
print(elementwise_product)


Matrix A:
[[4 7]
 [4 3]]
Matrix B:
[[1 7]
 [4 3]]
Element-wise product of matrices A and B:
[[ 4 49]
 [16  9]]


In [14]:
# Task 13: Create two additional 2x2 matrices with random integers from 1 to 10
mat_c = np.random.randint(1, 11, size=(2, 2))
mat_d = np.random.randint(1, 11, size=(2, 2))

print("Matrix C:")
print(mat_c)
print("Matrix D:")
print(mat_d)

# Calculate the matrix product
matrix_product = np.dot(mat_c, mat_d)
print("Matrix product of matrices C and D:")
print(matrix_product)


Matrix C:
[[ 7  4]
 [10  1]]
Matrix D:
[[ 4 10]
 [ 2 10]]
Matrix product of matrices C and D:
[[ 36 110]
 [ 42 110]]


In [15]:
# Task 14: Create a 5x5 matrix with random integers from 1 to 100
matrix_5x5_100 = np.random.randint(1, 101, size=(5, 5))
print("5x5 matrix with random integers from 1 to 100:")
print(matrix_5x5_100)

# Calculate the sum of all elements in the matrix
sum_elements = np.sum(matrix_5x5_100)
print("Sum of the matrix elements:")
print(sum_elements)


5x5 matrix with random integers from 1 to 100:
[[ 2 54 92 49 70]
 [43 98 26 76 68]
 [93  4 53 80 54]
 [39 63 22 80  3]
 [85 68 92 96 98]]
Sum of the matrix elements:
1508


In [16]:
# Task 15: Create two 4x4 matrices with random integers from 1 to 10
matrix_A = np.random.randint(1, 11, size=(4, 4))
matrix_B = np.random.randint(1, 11, size=(4, 4))

print("Matrix A (4x4):")
print(matrix_A)
print("Matrix B (4x4):")
print(matrix_B)

# Calculate the difference (Matrix A - Matrix B)
difference = matrix_A - matrix_B
print("Difference between matrices A and B:")
print(difference)


Matrix A (4x4):
[[9 8 6 9]
 [1 8 1 2]
 [6 6 5 8]
 [8 2 3 1]]
Matrix B (4x4):
[[10  5  1  9]
 [10 10  4 10]
 [ 5  5  7  3]
 [ 3  8  1  4]]
Difference between matrices A and B:
[[-1  3  5  0]
 [-9 -2 -3 -8]
 [ 1  1 -2  5]
 [ 5 -6  2 -3]]


In [17]:
# Task 16: Create a 3x3 matrix with random floats from 0 to 1
matrix_3x3_float = np.random.rand(3, 3)
print("3x3 matrix with random floats:")
print(matrix_3x3_float)

# Compute the sum of each row and reshape it to a column vector
row_sums = np.sum(matrix_3x3_float, axis=1).reshape(-1, 1)
print("Column vector with the sum of each row:")
print(row_sums)


3x3 matrix with random floats:
[[0.12459539 0.37966643 0.27726898]
 [0.98549256 0.18603872 0.65350303]
 [0.24687639 0.57159546 0.75924522]]
Column vector with the sum of each row:
[[0.7815308 ]
 [1.82503431]
 [1.57771707]]


In [18]:
# Task 17: Create a 3x4 matrix with arbitrary integers (for example, from 1 to 20)
matrix_3x4_int = np.random.randint(1, 21, size=(3, 4))
print("3x4 matrix with arbitrary integers:")
print(matrix_3x4_int)

# Create a matrix with the squares of each element
squared_matrix = np.square(matrix_3x4_int)
print("Matrix with squared elements:")
print(squared_matrix)


3x4 matrix with arbitrary integers:
[[ 9  2  7 10]
 [ 7  5 17  6]
 [ 5  1  8 15]]
Matrix with squared elements:
[[ 81   4  49 100]
 [ 49  25 289  36]
 [ 25   1  64 225]]


In [19]:
# Task 18: Create a vector of size 4 with random integers from 1 to 50
vector_4_int = np.random.randint(1, 51, size=4)
print("Vector with random integers from 1 to 50:")
print(vector_4_int)

# Compute the vector of square roots of the elements
sqrt_vector = np.sqrt(vector_4_int)
print("Vector with the square roots of the numbers:")
print(sqrt_vector)


Vector with random integers from 1 to 50:
[40 47 34 12]
Vector with the square roots of the numbers:
[6.32455532 6.8556546  5.83095189 3.46410162]
